# Generated by Django 4.1.2 on 2023-01-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_urltype_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='urltype',
            name='type',
            field=models.CharField(choices=[('malware', 'malware'), ('phishing', 'phishing'), ('adult', 'adult')], default='adult', max_length=20),
        ),
    ]
