# Generated by Django 4.1.2 on 2023-01-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urltype',
            name='type',
            field=models.CharField(default='adult', max_length=20),
        ),
    ]
