# Generated by Django 4.1.2 on 2023-01-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
